- name: Adding epel-release Repo
  become: yes
  yum:
    name: epel-release
    state: present

- name: Installing Nginx
  become: yes
  yum:
    name: nginx
    state: present

- name: Install Python 36 packages
  become: yes
  yum:
    name: python36
    state: present

- name: Deleting default Nginx conf
  become: yes
  file:
    path: /etc/nginx/conf.d/default
    state: absent

- name: Adding code dir
  become: yes
  file:
    path: /var/www/demo
    state: directory 
    mode: 0755
    owner: nginx
    group: nginx


- name: Adding html file
  become: yes
  copy:
    src: files/index.html
    dest: /var/www/demo/index.html
    mode: 0755
    owner: nginx     
    group: nginx


- name: Copy app nginx conf
  become: yes
  copy:
    src: files/demo.conf
    dest: /etc/nginx/conf.d/demo.conf
    mode: 755


- name: Copy ssl key
  become: yes
  copy:
    src: files/key.pem
    dest: /etc/ssl/key.pem
    mode: 744

- name: Copy ssl cert
  become: yes
  copy:
    src: files/cert.pem
    dest: /etc/ssl/cert.pem
    mode: 744

- name: Starting Nginx Server
  become: yes
  service:
    name: nginx
    state: started

